FROM node:8.12.0
MAINTAINER KinoTimes <admin@kinotimes.tk>

RUN mkdir /usr/app
WORKDIR /usr/app

# add JS
COPY package.json .
# For npm@5 or later
# COPY package.json package-lock.json ./
RUN npm install
COPY ./build ./build
COPY ./server.js ./server.js

ENV KT_PORT=80 REACT_APP_KT_URL=http://kinotimes.tk REACT_APP_KT_BACKEND_PORT=8888 REACT_APP_KT_PORT=3000 TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# REACT_APP_KT_PORT
EXPOSE 3000
CMD ["npm", "start"]
