FROM node:boron
MAINTAINER KinoTimes <admin@kintotimes.tk>

RUN mkdir /usr/app
WORKDIR /usr/app

# add JS
COPY package.json .
# For npm@5 or later
# COPY package.json package-lock.json ./
RUN npm install
COPY ./build ./build
COPY ./server.js ./server.js

ENV KT_PORT=80
ENV REACT_APP_KT_URL=http://kintotimes.tk
ENV REACT_APP_KT_BACKEND_PORT=8888
ENV REACT_APP_KT_PORT=3000

# REACT_APP_KT_PORT
EXPOSE 3000
CMD ["npm", "start"]
