version: "2"
services:

  worker:
    image: quay.io/grandvizier/kinotimes_backend:latest
    volumes:
      - ./:/app
    links:
      - mongo

  web:
    image: quay.io/grandvizier/kinotimes_web:latest
    volumes:
      - ./:/app
    ports:
      - "${KT_HOST_PORT}:8888"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"