version: "2"
services:

  backend:
    image: quay.io/kinotimes/backend:$BUILD
    volumes:
      - ./:/app
    links:
      - mongo
    ports:
      - "8888:8888"
    networks:
      - app-network

  web:
    image: quay.io/kinotimes/web:$BUILD
    volumes:
      - ./:/app
    ports:
      - "80:3000"
    networks:
      - app-network

  nginx:
    image: quay.io/kinotimes/nginx:$BUILD
    volumes:
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    links:
      - web:www.kinotimes.tk
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email knurek.stuff@gmail.com --agree-tos --no-eff-email --staging -d kinotimes.tk -d www.kinotimes.tk

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
