version: "2"
services:

  backend:
    image: quay.io/kinotimes/backend:latest
    volumes:
      - ./:/app
    links:
      - mongo
    ports:
      - "8888:8888"

  web:
    image: quay.io/kinotimes/web:latest
    volumes:
      - ./:/app
    ports:
      - "80:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
