language: node_js
node_js:
  - 6.9.4
branches:
  only:
    - master

env:
  global:
    - secure: ze/SrM7abm6jS/uEB3r4TBT2mCAvJouayuzcgOPfKiVh9z132IlW2R9FmNwzohsGw5l8EfWCDzwaTh4+rqbCH1XTGOz0CXa0AiVyB7OcuygYgznWo4OTAwGtJs8wRlcfufS5niQZhXdDY/OuQs0WtRmeSq0OPWbVpnTNgfc5QlZYQHYwLJELp0UghRkpWIHndtzre9bdNjasWKfLHAnF92F3/Pg/xDGvuoWRi/0OV9Jn9PG5VRw2m+Gu/aqq4MQhHWqqGmzgUEvBFIbF8AttuZslodC+UHqw8k02lDkQVbrfZfeoc1A9RMNg1/kg8Oi0DanWywodM9toD8mi84mUMg==
    - DOCKER_ACC=quay.io/kinotimes
    - CI=true
    - REACT_APP_KT_BACKEND_PORT=8888
    - REACT_APP_KT_PORT=3000
    - REACT_APP_KT_URL=http://kinotimes.tk

build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/backend/node_modules
    - $SHIPPABLE_BUILD_DIR/frontend/node_modules

  ci:
    - npm install -g create-react-app

    # build backend
    - shippable_retry cd $SHIPPABLE_BUILD_DIR/backend/; npm install

    # build frontend
    - shippable_retry cd $SHIPPABLE_BUILD_DIR/frontend/; npm install
    - cd $SHIPPABLE_BUILD_DIR/frontend/; npm test
    - shippable_retry cd $SHIPPABLE_BUILD_DIR/frontend/; npm run build

    # build docker images
    - docker build -f $SHIPPABLE_BUILD_DIR/frontend/Dockerfile.web -t $DOCKER_ACC/web:$BUILD_NUMBER $SHIPPABLE_BUILD_DIR/frontend/
    - docker build -f $SHIPPABLE_BUILD_DIR/backend/Dockerfile.backend -t $DOCKER_ACC/backend:$BUILD_NUMBER  --build-arg tmdb_token=$TMDB_TOKEN --build-arg omdb_apikey=$OMDB_APIKEY $SHIPPABLE_BUILD_DIR/backend/

  post_ci:
    - docker push $DOCKER_ACC/web:$BUILD_NUMBER
    - docker push $DOCKER_ACC/backend:$BUILD_NUMBER

integrations:
  hub:
    - integrationName: quay-integration
      type: quay.io

jobs:
  - name: deploy-to-prod
    type: deploy
    steps:
      - IN: pauls_vm
      - TASK:
        - script: cd /root/app
        - script: export BUILD=$BUILD_NUMBER; docker-compose up -d
