FROM node:boron
MAINTAINER KinoTimes <admin@kintotimes.tk>

# Add local cron file to the cron directory
RUN apt-get update && apt-get install -y cron
COPY ./.docker/film-cron /etc/cron.d/film-cron
RUN chmod 0644 /etc/cron.d/film-cron
RUN touch /var/log/cron.log

# add JS backend
WORKDIR /usr/src/app
COPY package.json .
# For npm@5 or later
# COPY package.json package-lock.json ./
RUN npm install
COPY . .

CMD cron && npm start
